### ISSUE TITLE
Feature: Propagate scheduleUpdate through nested poppers

### ISSUE THREAD

**Issue by tyscorp** [FezVrasta/react-popper#121]
When `scheduleUpdate` is called on a popper, it should call `scheduleUpdate` on all nested poppers. We can do this through context so it works through portals, too.

I'd be happy to take this on.

This would fix this issue: https://github.com/palantir/blueprint/issues/2031

**Comment by FezVrasta** [comment]
I'd ask you to hold on on this feature because we are going to replace the API completely in the next few days (see #117).

Anyway it's a good idea.

**Comment by tyscorp** [comment]
I could perhaps base my PR on `the react-16-major-rewrite` branch so we could get it into v1.0.0.

**Comment by FezVrasta** [comment]
I'm not sure if we are going to use that specific API or a mixture of the first iteration and the last one.

**Comment by FezVrasta** [comment]
The new API is now on beta and merged to `master`, please feel free to contribute on the new code base with your idea.

**Comment by tyscorp** [comment]
Ok, I'll need about 1 day I think. When is v1.0.0 set to release?

**Comment by FezVrasta** [comment]
I'm waiting few days to receive feedbacks, if everything is fine I'll release it then.
