### ISSUE TITLE
v1 beta 4: Obscure positioning issue

### ISSUE THREAD

**Issue by diondiondion** [FezVrasta/react-popper#134]
Hi FezVrasta, awesome new API! Now I don't have to write my own popper.js wrapper for react anymore :) 

I've stumbled across a really weird issue that causes poppers to be offset from their reference element by a bunch of pixels under some quite specific circumstances, took me quite a while to reproduce this using the repro template.

### Reproduction demo

- v1.0.0 beta 4: https://codesandbox.io/s/9nqn35m54

### Steps to reproduce the problem

1. **Center or right-align the reference element**
    (Any technique will do, in the demo I added `text-align: center` to `#root` and made the reference an inline-block, but you can also add `margin: 'auto',` or `marginLeft: 'auto',` to the reference element directly.)
2. Set the height and width of `html, body, #root` to 100% and remove default padding on the root.
   ```
     #root {
      margin: 0;
      /* padding: 20px; */
      text-align: center;
    }
     html, body, #root {
      width: 100%;
      height: 100%;
    }
   ```
3. Wrap the popper in a Portal

### What is the expected behavior?

- Poppers to be positioned flush around the edges of the reference.
   ![image](https://user-images.githubusercontent.com/5636050/38468776-053c4a2c-3b4b-11e8-8464-189f00043c81.png)

### What went wrong?

- Poppers are consistently offset to the left
   ![image](https://user-images.githubusercontent.com/5636050/38468763-ec0bd9c8-3b4a-11e8-85db-bcd4ede50b39.png)
   ![image](https://user-images.githubusercontent.com/5636050/38468784-1b22fcbe-3b4b-11e8-978a-98a26e0bf60c.png)
   ![image](https://user-images.githubusercontent.com/5636050/38468790-2630f76e-3b4b-11e8-9349-97687c25cc7b.png)

### Any other comments?

I think I remember this issue from an earlier version of react-popper, and it was solved by running scheduleUpdate again right after the first initialisation.
Resizing the window will also fix the issue temporarily.

Any idea what could be causing this issue?

### Packages versions

- react-popper: 0.10.1

**Comment by FezVrasta** [comment]
Umh what if I can't reproduce the issue? 😅

Browser?

**Comment by diondiondion** [comment]
I can reproduce this on any browser installed on my Mac: Chrome (65), Firefox (Nightly), Safari (11.1).

I just noticed it doesn't happen in mobile browsers. Makes me think it must be related to scrollbars.

**Comment by FezVrasta** [comment]
Ok reproduced, I think it may be related to this one
https://github.com/FezVrasta/popper.js/issues/510

**Comment by FezVrasta** [comment]
Ok this sucks, it's not related to FezVrasta/popper.js#510, but to the result that `getBoundingClientRect.js` returns when it's called the first time.

It returns a wrong value, the problem is that the value comes directly from `element.getBoundingClientRect()` so there's not much I can do to tell the !*#%☠︎ browsers to return the correct value 🙄

**Comment by FezVrasta** [comment]
Ok I confirm that with beta.5 the bug is fixed

**Comment by diondiondion** [comment]
Brilliant, I'll have a look soon. Thanks so much for the quick fix!
