### ISSUE TITLE
Upgrade Popper.js version

### ISSUE THREAD

**Issue by alexander-morozov** [FezVrasta/react-popper#136]
It'd be cool it you upgraded popper.js version as a lot of problems were fixed, especially this one:
https://github.com/FezVrasta/popper.js/issues/251

**Comment by FezVrasta** [comment]
The `package.json` already specifies `popper.js@^1.14.1`, this means that it will install the latest `1.x` available version.

- https://github.com/FezVrasta/react-popper/blob/master/package.json#L61
- https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers
