### ISSUE TITLE
v0.x demo does not build

### ISSUE THREAD

**Issue by nijk** [FezVrasta/react-popper#143]
### Steps to reproduce the problem

1.  `npm install`
2.  `npm run demo`
3.  Build error:
```
react-popper/demo/animated.jsx:68:2: /Users/nijk/dev/frontend/react-popper/demo/animated.jsx: Missing class properties transform.
  66 |
  67 | class AnimatedExample extends PureComponent {
> 68 |   state = {
     |   ^
  69 |     isOpen: false,
  70 |   }
  71 |
```

### What is the expected behavior?
The demo should build and run (I'm using the latest major node version)

### What went wrong?
I believe that the `babel-plugin-transform-class-properties` is required

### Any other comments?
I've also noticed that `package.json` is not handled either in the repo or via `.gitignore`

### Packages versions

- Popper.js: v0.x HEAD
- react-popper: n/a

**Comment by nijk** [comment]
@FezVrasta Shall I raise another PR to deal with the `package-lock.json` (misspelled the name of the file in the issue)

**Comment by FezVrasta** [comment]
Umh yeah I don't use npm so I never noticed it wasn't ignored, I just pushed a commit to ignore it.
