### ISSUE TITLE
v0.10.1 - SSR breaks because of React-Popper + No /dist builds in 1.0beta5

### ISSUE THREAD

**Issue by virgofx** [FezVrasta/react-popper#145]
The UMD build is broken in v0.10.1 because of:

`Manager.propTypes = process.env.NODE_ENV !== "production" ? {`

The production build should use plugin that optimizes and removes this code ahead of time. In Webpack it was the Define plugin. Then the remove prop-types plugin will correctly wrap it and leave it as `{}`.

What's the best way to resolve this?

0.10.1
> Rollup. I can find the corresponding plugin to ensure it optimizes it out and submit a PR for an immediate patch fix. Or are you not releasing updates anymore?

1.x.x
>  What's the situation here? There's currently no `/dist`. This is a huge problem. Reactstrap utilizes external opt-in dependency for Bootstrap and is a huge community. https://github.com/reactstrap/reactstrap

Ref: #142

**Comment by nijk** [comment]
@virgofx for v0.10.1 see [this issue I've raised with babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/140).

Basically the default mode that is supposed to entirely remove the propTypes from production builds is not working for React stateless functional components and therefore [I can't fix this issue](https://github.com/FezVrasta/react-popper/issues/142). As you've found in this issue `process.env.NODE_ENV` is not available in the browser _unless_ it is provided by something like the DefinePlugin in Webpack or similar in your own bundling process. This is a requirement that I'm not keen on either, but for now I would suggest that you do one of two things:

1. Find a way to provide `process.env.NODE_ENV` in your application (Server side by the sounds of it)
2. Raise a PR to entirely remove the [`babel-plugin-transform-react-remove-prop-types` plugin's usage](https://github.com/FezVrasta/react-popper/blob/v0.x/rollup.config.js#L12) from rollup.config.js

**Comment by virgofx** [comment]
I'm not sure about the stateless components; however, the issue with regards to process can be fixed quite easily. I'll submit a PR which fixes this.

**Comment by nijk** [comment]
@virgofx Try following the replication steps I've posted on that ticket about stateless functional components and you'll understand. The point is that `babel-plugin-transform-react-remove-prop-types` should work properly, but it doesn't because of a bug with removing propTypes from functional components that ReactPopper uses, which means we can just remove `{mode: wrap}` from the plugin config on `v0.x`.

**Comment by virgofx** [comment]
So seems to fix
1. Continue to use `mode: 'wrap'` but add the Rollup replace plugin -- which will clean that all up ... or
2. Just switch to `"removeImport": true` 

Regardless, the Rollup replace plugin (equivalent of Webpack's define) should be used regardless so my thought is to just leave as mode:wrap which is intended for libraries that may be consumed externally.

(Minus any areas with SFC that don't work) ... Regardless, server rendering should be fixed after that, correct?

**Comment by FezVrasta** [comment]
Fixed in 0.10.2
