### ISSUE TITLE
"ReferenceError: babelHelpers is not defined" in version 0.10.2 (not in 0.10.1)

### ISSUE THREAD

**Issue by davidxmoody** [FezVrasta/react-popper#160]
### Steps to reproduce the problem

1.  I'm using material-ui beta 44 which uses react-popper as a dependency (bundled with create-react-app typescript scripts)

### What is the expected behavior?

It should compile.

### What went wrong?

I get the following error:

```
ReferenceError: babelHelpers is not defined
(anonymous function)
node_modules/react-popper/lib/Manager.js:5
  2 | import PropTypes from 'prop-types';
  3 | 
  4 | var Manager = function (_Component) {
> 5 |   babelHelpers.inherits(Manager, _Component);
  6 | 
  7 |   function Manager() {
  8 |     var _ref;
```

### Any other comments?

Installing 0.10.1 manually fixes the problem. I can provide more info if necessary although given that the new version was only just released, I was hoping it would be an obvious fix.

### Packages versions

- Popper.js: 
- react-popper: 0.10.2

**Comment by FezVrasta** [comment]
@virgofx since you worked on the 0.10.2 changes, may you have a look?

**Comment by TrySound** [comment]
@FezVrasta external-helpers should be added only for rollup build. For babeled files it shouldn't not be added.

**Comment by FezVrasta** [comment]
0.10.3 fixes it

**Comment by virgofx** [comment]
@TrySound Can you check 0.10.3 and confirm fixed?

**Comment by FezVrasta** [comment]
The babelhelpers are not referenced in the file anymore so hopefully yes.

https://unpkg.com/react-popper@0.10.3/lib/Manager.js

But I just noticed that the `package.json` points to an invalid `main` path, is it still related to your PR maybe?

**Comment by virgofx** [comment]
I actually didn't change that (not too familiar with the `main` or `umd:main`) references. I'm sure you could submit a new PR to update those ...

**Comment by TheSharpieOne** [comment]
also consider `jsdelivr` and `unpkg` properties in the package.json (and maybe even `cdn`). They are properties which help the CDNs determine which file to server.
See:
https://github.com/unpkg/unpkg/issues/63
https://github.com/jsdelivr/jsdelivr#publishing-packages

**Comment by oliviertassinari** [comment]
0.10.3 introduce another problem:
package.json referrence `dist/react-popper.js` but it doesn't exist.

**Comment by oliviertassinari** [comment]
https://github.com/FezVrasta/react-popper/commit/65c3fb5c0786bb250454087d2de1489c55a19587

**Comment by FezVrasta** [comment]
0.10.4 should be fine hopefully
