### ISSUE TITLE
I can't use react-popper in NextJS in production env

### ISSUE THREAD

**Issue by Iliyass** [FezVrasta/react-popper#163]
### Steps to reproduce the problem

1.  integrate in our NextJS app
2.  build the prod version

### What went wrong?
The library works great in the dev env, but in prod env throws an error

### Packages versions

- react-popper: 1.0.0-beta.6
- react: 16.2.0
- next: 5.1.0

**Comment by FezVrasta** [comment]
Hey, thanks for the issue but you haven't provided enough information to help me understand what's happening.

Please feel free to add more details and I'll reopen it.
