### ISSUE TITLE
Suggestion: Add prop getters

### ISSUE THREAD

**Issue by alexandernanberg** [FezVrasta/react-popper#164]
First of all, great work on this lib!

My suggestion is to add prop getters similarly to how [downshift](https://github.com/paypal/downshift) does. This would in my opinion provide a much nicer implementation and prevent possible errors (eg. as forgetting to add the style).

So with prop getters the example would instead look something like this;

```javascript
import { Manager, Reference, Popper } from 'react-popper';

const Example = () => (
  <Manager>
    <Reference>
      {({ ref }) => (
        <button type="button" ref={ref}>
          Reference element
        </button>
      )}
    </Reference>
    <Popper placement="right">
      {({ getPopperProps, getArrowProps }) => (
        <div {...getPopperProps()}>
          Popper element
          <div {...getArrowProps()} />
        </div>
      )}
    </Popper>
  </Manager>
);
```

I'd be happy to add a PR if you are interested in this approach 😄

**Comment by FezVrasta** [comment]
Thanks for the suggestion, this was something that have been considered already in the past. [[1]](https://github.com/FezVrasta/react-popper/pull/117#issuecomment-378617383)

As mentioned in the issue I linked, I think they would make the API much harder to work with.

For instance, if you wanted to use the `placement` property on the arrow element, you would need to do some wizardry to call the `getPopperProps` twice, once to get all the props and apply them to the popper div, and once to get the placement prop and apply it to the arrow div.\
Additionally, you would need a way to map the `placement` prop to `data-placement`, or to any HTML attribute you prefer.

**Comment by alexandernanberg** [comment]
Oh I missed that thread! 

If I'm not misstaken my proposal is not exactly as the one you were talking about in that thread, but it might still have the same implications? 

Agree that merging css `transform` values would probably be a pain to do, but I don't see why you would want to do that? Isn't that how it works right now?

**Comment by FezVrasta** [comment]
Right now we don't merge any css property, but if we were to provide a props getter function that merges the user props with the ones of the library, I'm sure lot of people would be confused by the fact that they can't apply `transform: scale(1.5)` because it would get overridden by the styles of popper
