### ISSUE TITLE
Automatically set arrow position

### ISSUE THREAD

**Issue by alexandernanberg** [FezVrasta/react-popper#165]
### Reproduction demo

https://codesandbox.io/s/nrypzn1yyp

### Steps to reproduce the problem

1.  Go to the codesandbox link
2.  See that the popper is not align correctly (note the alignment)
3.  Remove the arrow element
4. See that the popper now aligns correctly

The issue also gets worse if you add padding to the popper element.

### What is the expected behavior?

For the popper to align properly to the reference element with the correct alignment even if you use an arrow.

### What went wrong?

The popper does not align correctly.

### Any other comments?

I haven't used popper.js or react-popper before today so It's possible that I'm missing something.

Could possible be related to #134

### Packages versions

- Popper.js: ^1.14.1
- react-popper: 1.0.0-beta.6

**Comment by FezVrasta** [comment]
Hey, you need to give `position: absolute` to the arrow element to have it to work properly.

I wonder if it may make sense to automatically set it together with the offsets 🤔

**Comment by alexandernanberg** [comment]
Ah of course, thanks for the quick reply! 

Yes, in my opinion it makes perfect sense to automatically set the `position`. Can't think of many cases when you wouldn't want that? Either way you can overwrite the value with your own css if you need something else right?

**Comment by giladgray** [comment]
@FezVrasta does this change (adding `position: absolute` to arrow styles) belong in this library or in popper.js itself?

**Comment by FezVrasta** [comment]
Good point. I think Popper.js sets `position` for the popper styles. If this is the case we should handle this at Popper.js level

**Comment by FezVrasta** [comment]
Closing, it's a problem that must be fixed in Popper.js itself
