### ISSUE TITLE
Wrapper or examples for tooltip?

### ISSUE THREAD

**Issue by 0xdevalias** [FezVrasta/react-popper#168]
It would be cool if there was a react wrapper (or usage examples) for: https://popper.js.org/tooltip-examples.html

**Comment by FezVrasta** [comment]
It's not something I'm going to implement in this project.

**Comment by bogdansoare** [comment]
why don't you want to integrate tooltips? I think it's the number 1 use case for popper and right now for react there aren't really decent tooltip libraries 

could you at least provide an example on how you would implement a tooltip with react-popper?

**Comment by joaoribeirost-rr** [comment]
@FezVrasta , I believe you'd get a lot of traction for usage if tooltip.js could be used along with this project. There aren't any good alternatives!

**Comment by denisborovikov** [comment]
Hi guys, please take a look at [react-popper-tooltip](https://github.com/mohsinulhaq/react-popper-tooltip) (this is not an official library).

**Comment by FezVrasta** [comment]
For anyone interested, I'm going to release in the next few hours the `@quid/react-tooltip` npm package, along with the existing `@quid/react-popover`. They do just what the name says 🙃

Feel free to take a look at the PR:
https://github.com/quid/refraction/pull/89

Or at the documentation for the popover:
https://ui.quid.com/#!/Popover
