### ISSUE TITLE
Making it easy to use an enclosing component as a boundariesElement

### ISSUE THREAD

**Issue by alaindresse** [FezVrasta/react-popper#170]
I was trying to use a react div as a container for a popper. I managed to set it up in the following [codesandbox](https://codesandbox.io/s/kx05r8vx17).

I was wondering if a similar solution could not be added 'structurally' to react-popper. The usage would be something like:

```javascript
  <ContainerManager>
    {({ containerRef, boundariesElement }) => (
      <div ref={containerRef}>
        <Reference>{({ ref }) => <div ref={ref}>Reference</div>}</Reference>
        <Popper boundariesElement={boundariesElement}>
          {({ ref, style, placement }) => (
            <div innerRef={ref} style={style} data-placement={placement}>
              Popup content
            </div>
          )}
        </Popper>
      </div>
    )}
  </ContainerManager>
```

The containerRef provided by the ContainerManager would set the boundariesElement that would then be passed to the Popper component.

Thanks,
Alain

**Comment by FezVrasta** [comment]
Hi, sorry for the delay.

I don't want to add APIs on top of Popper.js, I'd like to keep this as a thin layer between Popper.js and React.
