### ISSUE TITLE
Click outside

### ISSUE THREAD

**Issue by gormonn** [FezVrasta/react-popper#171]
Click outside popup doesn't appear?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by elie222** [comment]
For those using React, I created a gist of an HOC that you can attach to any component to close it when clicked outside:

https://gist.github.com/elie222/850bc4adede99650508aba2090cd5da1

**Comment by ziaulrehman40** [comment]
@elie222 Some explanation on how to use will be great

**Comment by elie222** [comment]
A click outside hook may be better nowadays
