### ISSUE TITLE
Tooltip fails to work with Material UI / Typescript / Next / Custom Server

### ISSUE THREAD

**Issue by tashburn** [FezVrasta/react-popper#172]
## Expected Behavior

Tooltips work.

## Current Behavior

When trying to use the Material UI 1.0.0 `Tooltip` with Next and Typescript, and visit `localhost:3000` with a browser, the following error happens in the console:

```
This dependency was not found:

* popper.js in ./node_modules/react-popper/lib/Popper.js

To install it, you can run: npm install --save popper.js
```

And the following error happens in the browser:

```
Error in ./Popper
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
ModuleNotFoundError: Module not found: Error: [CaseSensitivePathsPlugin] `/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/react-popper/lib/popper.js` does not match the corresponding path on disk `Popper.js`.
    at factoryCallback (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at applyPluginsAsyncWaterfall (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/webpack/lib/NormalModuleFactory.js:70:21)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/tapable/lib/Tapable.js:265:18
    at that.fileExistsWithCase (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:156:15)
    at that.getFilenamesInDir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:97:7)
    at fs.readdir (/Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/case-sensitive-paths-webpack-plugin/index.js:63:5)
    at /Users/trent/home/projects/Grok/tmp/issue-tooltip/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

If I try `yarn add popper.js`, the following warning is produced and the errors above remain --

```
warning Pattern ["popper.js@1.14.3"] is trying to unpack in the same destination "/Users/trent/Library/Caches/Yarn/v1/npm-popper.js-1.14.3-1438f98d046acf7b4d78cd502bf418ac64d4f095" as pattern ["popper.js@^1.14.1"]. This could result in non-deterministic behavior, skipping.
```

## Context

This is blocking my project.

## Steps To Reproduce

1. `git clone git@github.com:tashburn/issue-tooltip.git`
2. `cd issue-tooltip`
3. `yarn install`
4. `yarn dev`
5. open `localhost:3000` in browser

## Environment

macOS (latest)
Chrome (latest)
custom server (express)
`typescript@2.8.3`
`next@6.0.3`
`@material-ui/core@1.0.0`

**Comment by oliviertassinari** [comment]
@tashburn I'm in the process of upgrading Material-UI to react-popper@1. Let's see if this fix the problem.

**Comment by tashburn** [comment]
@oliviertassinari Fabulous. If you let me know when it's out, I'll test it with my sample repo.

**Comment by oliviertassinari** [comment]
https://github.com/mui-org/material-ui/pull/11862

**Comment by FezVrasta** [comment]
@oliviertassinari does this fix the OP problem?

**Comment by oliviertassinari** [comment]
I don't know.

**Comment by tashburn** [comment]
@FezVrasta I can check once the new `material-ui` version is obtainable via `yarn`.

**Comment by FezVrasta** [comment]
@tashburn any updates?

**Comment by tashburn** [comment]
Since 
@material-ui/core 1.2 to 1.3
typescript 2.9.1 to 2.9.2
"next": "6.0.3",

**Comment by oliviertassinari** [comment]
@tashburn I plan on revamping the tooltip implementation this weekend on Material-UI side. It's a mess right now. I will most likely use popper.js directly.

**Comment by FezVrasta** [comment]
I'd rather get help here to make react-popper work in your case, but it's up to you 😢

**Comment by tashburn** [comment]
@oliviertassinari Thanks for the update. I just checked to see if the new `@material-ui/core` version 1.3 fixed this tooltip issue I had with version 1.2 (same issue).

**Comment by oliviertassinari** [comment]
@FezVrasta Don't worry, the motivation for using popper.js directly is around the problems react popper solves. Digging into the implementation, I see an opportunity to make the implementation simpler & more lightweight. It might not execute. I will see how that goes.

**Comment by FezVrasta** [comment]
I'm going to close this for inactivity, I suppose the problem has been fixed already. If not please reply here.
