### ISSUE TITLE
what remains in 1.0?

### ISSUE THREAD

**Issue by giladgray** [FezVrasta/react-popper#175]
@FezVrasta how close are we to shipping official 1.0.0 here? are any features missing? 

i'm happy to help out! let me know what can be done.

**Comment by FezVrasta** [comment]
Thanks for the interest, there's #165 and I think we'd be good to ship the first stable

**Comment by giladgray** [comment]
@FezVrasta update here? #165 should be fixed in popper itself, so i think there's nothing left to do here?
