### ISSUE TITLE
Doesn't seem to work with React 15 although the README implies it should

### ISSUE THREAD

**Issue by somewhatabstract** [FezVrasta/react-popper#183]
### Reproduction demo
```
import * as React from "react";
import * as Popper from "react-popper";

class Test extends React.Component {
    render() {
        return (
            <div>
                <Popper.Manager>
                    <div>
                        <Popper.Reference>
                            {({ ref }) => (
                                <div ref={ref}>Test 2</div>
                            )}
                        </Popper.Reference>
                    </div>
                    <div>
                        <Popper.Popper>
                            {({ ref, style, placement, arrowProps }) => (
                                <div ref={ref}>Test</div>
                            )}
                        </Popper.Popper>
                    </div>
                </Popper.Manager>
            </div>
        );
    }
}
```

https://codesandbox.io/s/zr96k9j483

### Steps to reproduce the problem

1.  Go to https://codesandbox.io/s/zr96k9j483

### What is the expected behavior?

It should work.

### What went wrong?

It crashes. I suspect because it is relying on some behavior of React 16 somewhere internally.

### Packages versions

- Popper.js: 
- react-popper: 1.0.0@beta.6
- React: 15.6.2

**Comment by somewhatabstract** [comment]
Oh nevermind, just reading through the code, I now see that there should be ONE div around both popper and reference. Doh!

Closing.

**Comment by FezVrasta** [comment]
It's also pointed out in the readme:

> Using React <=15 or Preact? The components created with them don't support to return fragments, this means that you will need to wrap <Reference /> and <Popper /> into a <div /> to make react-popper work.

**Comment by somewhatabstract** [comment]
@FezVrasta Yes, I saw that but had misinterpreted it and put them both into their own divs. As soon as I realised my mistake in interpreting that, all was well. Thank you!

**Comment by FezVrasta** [comment]
If you can think of a better wording please send a PR to improve it
