### ISSUE TITLE
Placement issues when rerendering children with different data

### ISSUE THREAD

**Issue by alexandernanberg** [FezVrasta/react-popper#190]
### Reproduction demo

https://codesandbox.io/s/qv86zl9l24

### Steps to reproduce the problem

1.  Write "top" in the input field
2.  Select the "top-end" option
3.  Remove text inside the input field so that the value is "top" again
4. The popper element (autocomplete menu) will now overlap the reference element (the input field)

### What is the expected behavior?
That the popper element will reposition itself so it doesn't overlap the reference element. 

### What went wrong?
The popper element overlaps the reference element. Probably because it doesn't know when it's children has updated?

### Any other comments?
Think that this is a bug/new behavior in v1. In v0.x it works as expected: http://downshift.netlify.com/?selectedKind=Examples&selectedStory=react-popper&full=0&addons=1&stories=1&panelRight=0

It's also possible that I'm doing stuff wrong. I tried using the `scheduleUpdate` function, that fixes the original issue but feel like a real code smell and other broke other stuff.

### Packages versions

- Popper.js: 
- react-popper: 1.0.0

**Comment by FezVrasta** [comment]
yes it looks like Popper.js isn't able to compute the dropdown dimensions, probably because they change _after_ Popper.js measured them.

Ideally downshift should provide a way to call `scheduleUpdate` when the dropdown is re-rendered.

Or maybe it's enough to rely on the React life cycle methods, like I did here:
https://codesandbox.io/s/qkm58q0l4w

**Comment by alexandernanberg** [comment]
@FezVrasta Yea and `Downshift` actually provides a prop that handles that; `onStateChange`. The problem is that I have to "lift up" the `scheduleUpdate` function to be able to call it inside the `onStateChange` method. Like this https://codesandbox.io/s/oq9pj2288q. Doing this feels a lot like an anti-pattern imo.

Tried using the life cycle methods but they caused infinite-loops instead, if you add a `console.log` inside the `componentDidUpdate` in your example you'll see what I mean.

I also encountered a problem when setting `ref`s causing infinite-loops (when you need to share a ref between `react-popper` and `downshift`), but I should maybe open another issue for that?

**Comment by alexandernanberg** [comment]
Ah, I'll play around with the solutions you proposed! Thank you for taking your time to answering this 😄

**Comment by AMSzura** [comment]
According to Popper docs:

> "You can also trigger an update by setting new options to your Popper instance. This, internally, will call the update() method"

And so, this issue can be solved by adding a custom modifier to options with a reference value that will trigger popper update on change, e.g.:

    modifiers: 
      [
        {
         name: 'ref',
         options: value,
         },
       ],
