### ISSUE TITLE
TypeError: Object(...)(...) is not a function

### ISSUE THREAD

**Issue by galileo303** [FezVrasta/react-popper#192]
### What went wrong?

react-popper/lib/esm/Popper.js:132
11 | import { safeInvoke, unwrapArray } from './utils';
...
  130 |   key: 'render',
  131 |   value: function render() {
> 132 |     return unwrapArray(this.props.children)({
  133 |       ref: this.setPopperNode,
  134 |       style: this.getPopperStyle(),
  135 |       placement: this.getPopperPlacement(

react-popper/lib/esm/utils.js:8
export var unwrapArray = function unwrapArray(arg) {
  return Array.isArray(arg) ? arg[0] : arg;
};

then its waing TypeError: Object(...)(...) is not a function

### Packages versions

- Popper.js: 1.0.0
- react-popper:1.0.0

**Comment by FezVrasta** [comment]
Sorry, I can't help if you don't provide the reproducible example, it seems like a problem related to your own project code anyway, nothing I can help you with.
