### ISSUE TITLE
Configuring flip functionality breaks the flipping

### ISSUE THREAD

**Issue by behzads** [FezVrasta/react-popper#194]
Hi,

Configuring flip using modifiers breaks the flipping functionality.
This is a blocker issue for us, I've made an example to see it in action.
https://stackblitz.com/edit/react-wp6kam?file=index.js

Thanks

**Comment by behzads** [comment]
Any updates on this issue?

**Comment by FezVrasta** [comment]
So actually it's the way you configured the modifier that's wrong, you are telling the flip modifier that the allowed flip placements are `top`, `right`, and `left`, but you position it on `bottom`. So it gets confused.

I understand it's not a good behavior, but it's a Popper.js issue.

I hope this will get better once I release Popper.js@2
