### ISSUE TITLE
Expose ManagerContext

### ISSUE THREAD

**Issue by jamiewinder** [FezVrasta/react-popper#195]
I'm upgrading a library of mine to use the newest version of React-Popper. One of the things my library adds is the ability to use a 'fake' reference rather than a component (similar to [how Popper.js allows for a referenceObject to be used](https://popper.js.org/popper-documentation.html#referenceObject)).

This is what it looked like (in TypeScript):
```typescript
export interface IPseudoTargetProps {
    reference: PopperJS.ReferenceObject;
}

export class PseudoTarget extends React.Component<IPseudoTargetProps> {
    // Static Fields
    public static readonly contextTypes = {
        popperManager: PropTypes.object.isRequired,
    };

    // Methods (React.Component)
    public render() {
        return null;
    }

    public componentDidMount() {
        this._setTargetNode();
    }

    public componentDidUpdate() {
        this._setTargetNode();
    }

    // Methods
    private _setTargetNode() {
        const { reference } = this.props;
        const { popperManager } = this.context;
        popperManager.setTargetNode(reference);
    }
}
```
As you can see, this uses the `popperManager` context, which in the new version is using the new React Context API, but this isn't exposed. 

Unless there is a better way of doing the above, is there a chance that the ManagerContext could be exposed so I can port it over?

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/react-popper#usage-without-a-reference-htmlelement

**Comment by jamiewinder** [comment]
Wow that was quick! Thanks. And sorry I didn't think to check the README as I thought it was a bit of a weird use case.
