### ISSUE TITLE
Typescript: [ts] Module '"react-popper"' has no exported member 'Reference'.

### ISSUE THREAD

**Issue by ricokahler** [FezVrasta/react-popper#196]
### Reproduction demo

![image](https://user-images.githubusercontent.com/10551026/42344329-0341afc8-806a-11e8-82db-303a48a4d8cb.png)

### Steps to reproduce the problem

1.  find/create a ts-react app
2.  install `react-popper`
3.  try to import `Reference`

### What is the expected behavior?

Working import

### What went wrong?

I may be missing something, but it looks like the typings that come with the library are not up to date. They look like v0.1 typings

### Any other comments?

Thanks for the great library. I'd be willing to add the typings in a PR if I get your blessing if this is found to be an issue.

### Packages versions

- react-popper: `"react-popper": "^1.0.0",`

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/react-popper/blob/master/typings/react-popper.d.ts

These are the types. Are you maybe using external types from def typed that are overriding the built in ones?

**Comment by FezVrasta** [comment]
I'm not sure, sorry.
