### ISSUE TITLE
Poppers are not getting placed properly

### ISSUE THREAD

**Issue by ralphsmith80** [FezVrasta/react-popper#198]
### Reproduction demo

https://codesandbox.io/s/o54lj508r5

### Steps to reproduce the problem

1.  Run the demo provided

### What is the expected behavior?

Poppers should be visible around the reference element

### What went wrong?

I pulled out a small bit of the demo provided and converted it to JSS to try an understand why this wasn't working in a real world project. I'm stuck with the poppers not being rendered as expected. The issues I've noticed are

1. The poppers always have `opacity: 0` and `pointer-events: 'none'` style properties.
2. The poppers are not placed relative to the `Reference`. This maybe related to the the `placement` property coming back as `undefined`. 

### Any other comments?

I've put some `console.logs` with question in the code to indicate where I've identified the problems. 

### Packages versions

- Popper.js: 
- react-popper: 1.0.0

**Comment by FezVrasta** [comment]
I'd start looking at why the "Dot" components are not properly positioned, in the demo the tooltips are relative to them, so if they are not working properly everything may be related

**Comment by ralphsmith80** [comment]
It looks like there an issue with how `refs` are being handled. I've paired this down to just a react-popper example and the issue arises when the Popper has a nested Component. 

[bare-react-popper example|https://codesandbox.io/s/rmknnvzw1m]
_If you comment out the second Popper that contains a Custom Component it works fine._

Note this works (nested div):

```
<Popper placement={activePlacement}>
  {({ ref, style, placement, arrowProps }) => {
    console.log(placement);
    return (
      <div
        ref={ref}
        style={style}
        data-placement={placement}
        onClick={setActivePlacement}
      >
        Popper element
      </div>
    );
  }}
</Popper>
```

This does not (custom component that return a div):

```
<Popper placement={activePlacement}>
  {({ ref, style, placement, arrowProps }) => {
    console.log(placement);
    return (
      <Dot
        ref={ref}
        style={style}
        // data-placement={placement}
        onClick={setActivePlacement}
        title={placement}
      />
    );
  }}
</Popper>
```

Dot looks like this

```
class Dot extends React.Component {
  render() {
    return <div {...this.props}>Popper element</div>;
  }
}
```

React Version: 16.3.2

**Comment by FezVrasta** [comment]
with `<Dot ref={ref} />` you are getting the Dot instance, not its DOM node.

You should use `React.forwardRef` to make it return the underlaying DOM node.

**Comment by ralphsmith80** [comment]
Thanks @FezVrasta! I though I might be messing that up. I still need to see if this will translate to the jss example. Ref forwarding is suppose to be supported by `react-jss` so I'm not sure why that was working from my original example.

For other `Dot` now looks like this:

```
const Dot = React.forwardRef((props, ref) => (
  <div ref={ref} {...props}>
    Popper element
  </div>
));
```

And the example work for the bare setup.
