### ISSUE TITLE
InnerPopper re-rendering and setting state unnecessarily

### ISSUE THREAD

**Issue by martinmckenna** [FezVrasta/react-popper#200]
### What went wrong?

Upon submitting a form (which contains a material-ui tooltip, which relies on `InnerPopper`), I navigate the user to a different page. When this happens, I get this console error

```
index.js:2177 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in InnerPopper
    in Popper (created by Tooltip)
    in Portal (created by Tooltip)
    in Manager (created by Tooltip)
```

### Any other comments?

I'm using material-ui v1.2.2.

It also seems like the InnerPopper is rendering on page scroll. Opening up React dev tools and highlighting re-renders shows me this

![rerender](https://user-images.githubusercontent.com/7387001/43005895-35c6f3d8-8c02-11e8-84e0-1a1bb2c04105.gif)

This is the element that's re-rendering (not totally sure if it's `InnerPopper`

```html
<div style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(678px, 431px, 0px);"></div>
```

I suggest you implement some sort of `isMounted` check before setting state

i.e

```
componentDidMount() {
  this.mounted = true;
}

.....

if(!this.mounted) {return}
this.setState({......})
```

### Packages versions

- Material-ui: 1.2.2

**Comment by FezVrasta** [comment]
This should fix it https://github.com/FezVrasta/react-popper/pull/197
