### ISSUE TITLE
Popup not shown on hover

### ISSUE THREAD

**Issue by Kadrian** [FezVrasta/react-popper#202]
### Reproduction demo

https://codesandbox.io/s/y7k66rkmoz

### Steps to reproduce the problem

1.  Open codesandbox
2. Paste example from Readme

### What is the expected behavior?

The popup shows upon hovering on the "Hover me" element.

### What went wrong?

The popup is always displayed, completely un-styled.

### Any other comments?

Maybe I'll need to import popper.js somehow before? Maybe I have the wrong expectations? Or I forgot to read some documentation?

### Packages versions

- Popper.js: 1.14.3
- react-popper: 1.0.0

**Comment by FezVrasta** [comment]
react-popper doesn't handle any show/hide logic, it's just handles positioning. Take a look at react-tippy for a full fledged tooltip component.

**Comment by Offirmo** [comment]
@FezVrasta Shouldn't that be clearly outlined 1 thing on top of the README?

https://popper.js.org/ hints strongly at tooltips.

**Comment by FezVrasta** [comment]
@Offirmo the Popper.js website mentions tooltips just twice, one as an example of something you can position with it, and once to guide the user to Tooltip.js, the library specialized in tooltips logic.

The example doesn't work as intended because the popper element is a `div` with its default `100%` width.

**Comment by chinmayjoshi195** [comment]
@FezVrasta So I wont be able to add the PopUp on Hover using just react-popper?

**Comment by mohsinulhaq** [comment]
@chinmayjoshi195 https://github.com/mohsinulhaq/react-popper-tooltip
you can use react-popper-tooltip for that
