### ISSUE TITLE
Poper placed incorrectly when created conditionally

### ISSUE THREAD

**Issue by rborosak** [FezVrasta/react-popper#206]
I'm using react-popper to show my calendar item above input element if there is no space bellow. My code is pretty straight foward
```jsx
<Manager>
            <Reference>
                {({ ref }) => (
                    <div ref={ref} >
                        <InputContainer width={this.props.width}>
                            <button tabIndex={-1} className='f4b-select-dropdown-button' onClick={() => this.onOpenDropDownClick()}>                     
                            </button>
                        </InputContainer>
                    </div>
                )}
            </Reference>
            <Popper placement='bottom-start'>
                {({ ref, style, placement }) => (
                    <div ref={ref} style={style} data-placement={placement}>
                        <DropdownHoc handleClickOutside={this.closeDropDown}>
                            {this.state.isOpened ? <div>{this.renderCalendar()}</div> : null}
                        </DropdownHoc>
                    </div>
                )}
            </Popper>
</Manager>
```

When my component is at the bottom of the screen and I press the button, calendar is diplayed bellow the input and vertical scrollbar appears. When I start scrolling my calendar repositions itself above the input element. After closing and opening it again everything works. I have played around and found that if I render some hidden div with height that about the height of my calendar then everything works, something like this (div instead of null)
` {this.state.isOpened ? <div>{this.renderCalendar()}</div> : <div style={{height:'200px'}}></div>}`

Is there an issue with popper react?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by yairEO** [comment]
I'm scratching my head on how to actually use `scheduleUpdate` conditionally inside JSX with some state changes..

**Comment by FezVrasta** [comment]
#190 has some good insights

**Comment by yairEO** [comment]
I've read that other thread before posting my comment, and could not understand what is this mysterious 

    <DownShift onStateChange

I mean, where that THIS comes from? i googled `onStateChange` got nothing. 

posted my question on [stackoverflow](https://stackoverflow.com/q/52295640/104380)

**Comment by FezVrasta** [comment]
I replied to your StackOverflow question.
