### ISSUE TITLE
react-popper requirejs configuration

### ISSUE THREAD

**Issue by bchoddny** [FezVrasta/react-popper#208]
Hi,
I've the following CDN links in my bower.json 

    "react-popper": "https://unpkg.com/react-popper/dist/index.umd.js",
    "popper.js": "https://unpkg.com/popper.js",

My requirejs config has the following:
        'react-popper': '../components/react-popper/index',
        'popper': '../components/popper.js/index',

When I load the page, I keep getting the error, wondering why it is not picking up the path from requirejs config. This path has the files.:

Uncaught Error: Script error for: popper.js

Please advise.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
