### ISSUE TITLE
Should we really install @next as stated in the doc?

### ISSUE THREAD

**Issue by Offirmo** [FezVrasta/react-popper#209]
Documentation issue here.

Current popper version is `1.0.2`

The README prompts us to install `react-popper@next`, which installs `1.0.0-beta.6`

Shouldn't we drop the `@next` ?

**Comment by FezVrasta** [comment]
That's right, the docs are outdated, please may you send a PR to fix it?

**Comment by Offirmo** [comment]
Will do.
