### ISSUE TITLE
Rendering tooltip-arrow with "referenceElement"

### ISSUE THREAD

**Issue by doneumark** [FezVrasta/react-popper#212]
Hi, I'm trying to create a popper that uses DOM Element to create some kind of a tooltip.
I need the Arrow component to work, and I can't managed to understand how to add it to my implementation:
```
<Popper
    referenceElement={element}
    placement='right'
>
    {({ ref, style, placement, arrowProps }) => (
        <div ref={ref} style={style} data-placement={placement}>
            Popper element
            <div ref={arrowProps.ref} style={arrowProps.style} />
        </div>
    )}
</Popper>
```

This current code, produce a regular div as a tooltip, with no arrows.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
