### ISSUE TITLE
No way to stick to position initially decided by the flip modifier

### ISSUE THREAD

**Issue by dvp0** [FezVrasta/react-popper#216]
https://codesandbox.io/s/yj0l1w5yrj

I want popper flip functionality to decide initial placement and than want to turn off the flip automation. In other words, want it to stick to that initial placement regardless of how I scroll.

Any way to do this easily ?

**Comment by FezVrasta** [comment]
You may achieve this by disabling the `flip` modifier after you received a new `placement` from the `onUpdate` callback.

**Comment by dvp0** [comment]
@FezVrasta There is no onUpdate in react-select@1.0.2 :)

interface PopperProps {
  children: (props: PopperChildrenProps) => React.ReactNode;
  eventsEnabled?: boolean;
  innerRef?: RefHandler;
  modifiers?: PopperJS.Modifiers;
  placement?: PopperJS.Placement;
  positionFixed?: boolean;
  referenceElement?: PopperJS.ReferenceObject;
}

**Comment by FezVrasta** [comment]
You can also define a custom modifier to mimic the onUpdate callback. Just run it after all the other modifiers
