### ISSUE TITLE
onClick doesn't work on mobile device

### ISSUE THREAD

**Issue by adityatandon007** [FezVrasta/react-popper#218]
This is in reference to an earlier closed issue #217 
### Steps to reproduce the problem

1.  https://codesandbox.io/s/842xlk8v99

### What is the expected behavior?
First of all I am not able to reproduce my original bug in codesandbox. The issue is with the `onClick` attached to the div. It doesn't fire in mobile devices. I am using react 15.6.0

The onClick event should fire on mobile devices.
### What went wrong?
Two things went wrong. 

First unable to reproduce the original bug in codesandbox.
The `onClick` attached inside the `div` of  the `<Popper/>` doesn't fire on mobile devices.
### Any other comments?
Awesome library though docs can be improved a bit with more simplistic examples.

### Packages versions

- Popper.js: 
- react-popper: 1.0.2
- React- 15.6.0

**Comment by adityatandon007** [comment]
@FezVrasta any help would be great.

**Comment by FezVrasta** [comment]
Sorry without a working demo I can't help.

**Comment by adityatandon007** [comment]
@FezVrasta I have come to the conclusion of why click on mobile wasn't working in my case. Basically the issue is with chrome only, in other browsers it was working and so I researched a bit and got that chrome made some breaking changes for handling touches and because I was preventing default and handling it myself it wasn't working. Here is quick reference https://github.com/facebook/react/issues/9809#issuecomment-414072263
and although react has fixed this it in version 16 but since I am still using react 15 i had to do it myself. Sorry for the trouble though and thanks for this wonderful library again.
