### ISSUE TITLE
Popper input focus issue

### ISSUE THREAD

**Issue by mohsinulhaq** [FezVrasta/react-popper#223]
### Reproduction demo
https://vyljw1lpjy.codesandbox.io/

### Steps to reproduce the problem

1. Have the reference such that it's not visible when you scroll to top. 
2.  Keep an input as popper that focuses itself on mount.
3.  Trigger the popper

### What is the issue?
Since initially the popper renders at `top: 0` and `left: 0`, the focus make the scroll jump to top.
I would need a hook for when popper.js has completed positioning the popper. Then I can call the focus method on the input.

### Packages versions
- react-popper: 1.0.2

**Comment by FezVrasta** [comment]
Thanks for the issue.

Maybe you can set `autoFocus` to `false` until react-popper properly set the offsets?

**Comment by mohsinulhaq** [comment]
okay, but how do you suggest I do that? polling?

**Comment by FezVrasta** [comment]
You can listen to the first `onUpdate` callback

**Comment by mohsinulhaq** [comment]
I'm sorry, but it's not clear on the docs where to send the defaults onUpdate prop. Could you please help? Apologies if I missed it.

**Comment by mohsinulhaq** [comment]
Yes, that would do. Thanks a lot. By the way, awesome library! I have created a tooltip library on top of it.  https://github.com/mohsinulhaq/react-popper-tooltip
Thanks for your library! 😃 
Closing the issue.

**Comment by mohsinulhaq** [comment]
hey I was wondering why haven't you made all you components as PureComponent?

**Comment by mohsinulhaq** [comment]
![image](https://user-images.githubusercontent.com/7688231/47081097-5667c980-d227-11e8-8d47-4687376afc36.png)
I am asking this because I see this warning using `why-did-you-update` on every render

**Comment by mohsinulhaq** [comment]
@FezVrasta ?

**Comment by FezVrasta** [comment]
Sorry I'm on vacation. Feel free to send a PR to reduce the avoidable rerenders
