### ISSUE TITLE
Allow warning 4.x

### ISSUE THREAD

**Issue by ekohl** [FezVrasta/react-popper#226]
Warning 4.x is out. The breaking changes are a license change and internals. Updating it shouldn't cause issues.

**Comment by FezVrasta** [comment]
Feel free to send a PR please!

**Comment by ekohl** [comment]
Do you prefer to change it to `^4.0.0` or `>= 3.0.0 < 5.0.0`?

**Comment by FezVrasta** [comment]
I think the second is better, if both can work I can see the value in allowing both
