### ISSUE TITLE
Exposing PoppperJS trough the library

### ISSUE THREAD

**Issue by asturur** [FezVrasta/react-popper#228]
Hi everyone,

Hi recently opened #224 that i realize is a poor solution to the problem.

The problem is that you may need to access to popper defaults in order to build an object that is compatible with the propTypes.

Matching your Popper with the one from react-popper is complicated and if often get a double boundling with webpack.

I would like to suggest to add PopperJS to the exports of react-popper in order to access defaults.

I would submit a green PR but i have flowJS test failing and i have no idea how to fix them

**Comment by FezVrasta** [comment]
For anyone interested in a solution, I expressed my opinion in #244.
