### ISSUE TITLE
`arrowProps.style.left` and `arrowProps.style.top` not updating

### ISSUE THREAD

**Issue by bgando** [FezVrasta/react-popper#229]
### Reproduction demo

https://codesandbox.io/s/40o490xm5w

### Steps to reproduce the problem

1.  `console.log(arrowProps.style)` within the popper element
2.  resize window or move reference element
3.  `arrowProps.style` does not update the `left` or `top` props

### What is the expected behavior?
I'd expect the `arrowProps.style.left` prop to track the reference element.

### What went wrong?
The `arrowProps.style.left` property does not change or track the element.

### Any other comments?
Cross-posted: https://spectrum.chat/thread/2216eaad-b72e-4e12-94d1-25f79d725d61

Thanks!

### Packages versions

- Popper.js: 1.14.4
- react-popper: 1.0.2

**Comment by FezVrasta** [comment]
I answered your question on our spectrum.chat

**Comment by bbalan** [comment]
@FezVrasta I have the same problem, can you post the answer here?

**Comment by kumarharsh** [comment]
@bbalan - you can follow the chat to see the answer - it's public.

> The CSS is wrong, the arrow should have position: absolute, https://codesandbox.io/s/4r6rrqzm9
