### ISSUE TITLE
How to change Popper.Defaults.modifiers...

### ISSUE THREAD

**Issue by Madyuskin** [FezVrasta/react-popper#233]
Hello, I use reactstrap and I need to change a static property.
The creation of Popper is deep inside.
I cannot pass props to it.

How can I set the following?

Popper.Defaults.modifiers.computeStyle.gpuAcceleration = false;

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
