### ISSUE TITLE
Missing (peer-)dependency on @types/react

### ISSUE THREAD

**Issue by mgroenhoff** [FezVrasta/react-popper#234]
`react-popper` is missing a (peer-)dependency on `@types/react`.

**Comment by TrySound** [comment]
It will be annoying for not typescript users.

**Comment by mgroenhoff** [comment]
It will also be a hell for TypeScript users to install every missing required dependency by themselves. `react-popper` chose to include TypeScript types so it should also take the responsibility to declare it's dependencies. Non-TypeScript users wil not notice the difference.

**Comment by TrySound** [comment]
Well, then it should be a direct dependency, but not peer.

**Comment by TrySound** [comment]
I also don't think you will miss to add react in react-ts project.

**Comment by mgroenhoff** [comment]
A direct dependency would be perfect.

I think you are missing the point here. If you have a dependency on a 3rd party dependency you add it to your package.json instead of asking users to also add this package as a dependency in the documentation. If everybody does not add their @@types@ dependencies because it is "annoying" then we might as well just push them all back to DefinitelyTyped. Then there is no point in bundling TypeScript types with packages if all dependencies are missing (even if obvious).
