### ISSUE TITLE
Doesn't work on React >= 16.3.0

### ISSUE THREAD

**Issue by funktr0n** [FezVrasta/react-popper#236]
Hey guys, it seems this library doesn't work on React versions greater than 16.3.0.  As the readme doesn't explicitly say that this is the case, I was just wondering what the expectation should be.

### Reproduction demo

https://codesandbox.io/s/82z77xw7v8

### Steps to reproduce the problem

1.  Update dependency from React 16.2 to React 16.3

### What is the expected behavior?

I would expect there not to be an error

### What went wrong?

There is an error... More specifically: 

```
Invariant Violation
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Manager`.
```

### Packages versions

- Popper.js: 
- react-popper: 1.0.0-beta 4
- React: 16.3

**Comment by funktr0n** [comment]
Realized that I needed to change `React-Dom` to match the `React` package used -- everything works as expected after doing that.

**Comment by mhayes** [comment]
@funktr0n Was just running into a similar issue with `react@16.6` and realized `react-dom` wasn't a matching version. Thank you for reporting the fix!
