### ISSUE TITLE
Any special cases where css transform is not applied?

### ISSUE THREAD

**Issue by ivanakimov** [FezVrasta/react-popper#238]
Quick question: are there any scenarios where `transform: translate3d(...)` is not added to `<Popper />`? Half of my poppers don't have the right position (anchored at the top left) and it looks like the only difference is `transform` is not applied on those..

**edit:** actually analyzing the `style` property, looks like it's returned as `translate3d(NaNpx, NaNpx, 0)` in a few cases.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by kristojorg** [comment]
@ivanakimov did you figure this out?

**Comment by ivanakimov** [comment]
@kristojorg Yeah we did. Since the original author was useless on this issue, we had to do some debugging. Turns out once we wrapped our content in a `<div>` inside `<Popper>` it started working ok.

**Comment by kristojorg** [comment]
@ivanakimov that was a bit rude to the creator of an open source lib. He's not getting paid to debug your issues. Thanks for the suggestion, though.
