### ISSUE TITLE
How do I make popper flip inside on the same side

### ISSUE THREAD

**Issue by mohsinulhaq** [FezVrasta/react-popper#247]
### Reproduction demo

https://codesandbox.io/s/2zjjvxz0qj

### Steps to reproduce the problem
 
1.  Click to open a right placed popper.
2.  Since there is not space on the right, it flips to left and since there is no space on the left as well, it pushes inside.

### What is the expected behavior?
It shouldn't flip like this when there is no space left as well as right. Instead it would be ideal to remain on the same side, just pushed inside.

### Packages versions

- react-popper: 1.0.2

Apologies if there is already a configuration for this.

**Comment by mohsinulhaq** [comment]
I just found out that there is a modifier named inner that does this, but it always makes popper render inside. I want it to do whenever there is not space at the specified placement prop.

**Comment by mohsinulhaq** [comment]
@FezVrasta any solution?

**Comment by FezVrasta** [comment]
It's not supported. A custom modifier can do that

**Comment by mohsinulhaq** [comment]
thanks for replying, could you please give some hint at least on how a custom modifier would achieve that?

**Comment by FezVrasta** [comment]
You should replace the built in flip modifier and make it apply the inner modifier when you want it to

**Comment by mohsinulhaq** [comment]
alright, thanks a ton. I will try this :)

**Comment by mohsinulhaq** [comment]
hi @FezVrasta, could you please tell me how do I do the overriding of flip modifier? I want it to call the orginal flip modifer + some things...right now it seems, once if use the custom flip fn function, the original behviour can't be accessed.

**Comment by mohsinulhaq** [comment]
https://stackoverflow.com/questions/53554105/how-to-reuse-popper-js-modifier-when-overriding-it
done

**Comment by mohsinulhaq** [comment]
hi, @FezVrasta do i need to provide more info on the question? please help
