### ISSUE TITLE
create-react-context (0.2.3) changed to non-open source

### ISSUE THREAD

**Issue by jEnbuska** [FezVrasta/react-popper#249]
create-react-context license has changed on 0.2.3
https://github.com/jamiebuilds/create-react-context/blob/v0.2.3/LICENSE

### Fix
change create-react-context dependency from "0.2.1^" to "0.2.2"

**Comment by FezVrasta** [comment]
Fixed, thanks!

**Comment by robinvdvleuten** [comment]
Is it really needed to point to 0.2.2 or below just for this license "change"? Other popular React libraries did not care about this change either. And now I have multiple versions of `create-react-context` in my build;

```bash
create-react-context (Found 2 resolved, 2 installed, 3 depended. Latest 0.2.3.)
  0.2.2 ~/react-popper/~/create-react-context
    ROOT@* -> react-popper@^1.3.3 -> create-react-context@<=0.2.2
  0.2.3 ~/create-react-context
    ROOT@* -> formik@^1.5.1 -> create-react-context@^0.2.2
    ROOT@* -> react-router-dom@^5.0.0 -> react-router@5.0.0 -> create-react-context@^0.2.2
```

**Comment by FezVrasta** [comment]
Yes it is important but I think the author switched back to an open source license so I'd say we can upgrade the package.json to allow recent versions as well
