### ISSUE TITLE
Mocking popper.js for Jest tests (attempting to help conversation locked in #82)

### ISSUE THREAD

**Issue by bkoltai** [FezVrasta/react-popper#263]
Sorry for opening a new issue that isn't really an issue, I just ran into some challenges getting `popper.js` mocked for `jest` tests and came across #82. I'm opening this issue because I can't leave a comment on that issue as it's now closed, but I wanted to share my solution that doesn't require me to include `popper.js` as a dependency of my project but still allows me to mock it out for tests that use `react-popper`

In `<root>/__mocks__/popper.js.js`
```javascript
const PopperJS = jest.requireActual('popper.js');

export default class {
  static placements = PopperJS.placements;

  constructor() {
    return {
      destroy: () => {},
      scheduleUpdate: () => {}
    };
  }
};
```

Using `jest.requireActual('popper.js')` resolves @jony89's [comment](https://github.com/FezVrasta/react-popper/issues/82#issuecomment-375278491) about needing to explicitly include `popper.js` as a dependency in my project.

Hope this helps, sorry again for opening an non-issue issue.

**Comment by FezVrasta** [comment]
Thanks! Marked as "docs and examples" to make it easy to find, I'll close it now.

**Comment by jmarceli** [comment]
Awesome, this might be linked with https://github.com/FezVrasta/popper.js/issues/478

**Comment by apieceofbart** [comment]
I had to add ` disableEventListeners: () => {}` for tests to work
