### ISSUE TITLE
Horizontal flipping of popper breaks when reference is on edge of screen

### ISSUE THREAD

**Issue by jakub-chatrny** [FezVrasta/react-popper#264]
I'm using `Popper` prop `placement` to set horizontal position `bottom-start/bottom-end`.
When reference is not on edge flipping works as expected. However when reference is on edge (left or right) flipping breaks and popper element is drawn outside viewport.

Is there any modifier to achieve this funcionality or is it `popper.js` bug?

https://codesandbox.io/s/7j86zzz391

**Comment by jakub-chatrny** [comment]
Ok I've came with solution. I needed to add modifier:
```
<Popper
        ...
        modifiers={{
          hide: {
            enabled: false
          },
          preventOverflow: {
            enabled: false
          }
        }}
>
```
I've updated my sandbox example above.

But I still have problem with popper outside viewport, they stretch my body element and make it scroll

**Comment by jakub-chatrny** [comment]
So far I did not. We decided this is minor issue so we might put effort to work around this issue in future.

But as you said it seems like `popper.js` issue.

**Comment by FezVrasta** [comment]
I'd kindly ask you to open an issue on the Popper.js repository following its issue template please.
