### ISSUE TITLE
Help with absolutely positioned elements

### ISSUE THREAD

**Issue by chrisdel101** [FezVrasta/react-popper#265]
### Reproduction demo
https://codesandbox.io/s/ywy5qyk93x

### Steps to reproduce the problem
This is not a bug. I just need help positioning over my aboluletly positioned 'stops' in a graph. I am trying to get the example (the main example from the repo page I mean) to work without much modification since I am a new user to popper. 

It works with the example button (if I paste the main example into my code) but not with my stops.

1.  On load - Stop is set as a reference element but popper is positioned in the top right hand corner of the graph, and not next to each stop.

### What is the expected behavior?
I want the poppers to be next to all the stops. The blue icons near the bottom of the graph are the stops.

I expect the popper to go next to the stops but I am not sure if they will work since I am absolutely positioning the stops with the inline style tag in React.  

**Possible solution**
The poppers have absolute positioning all set to zero currently. I could feed the poppers the coords I use for my stops. They are CSS. I just thought I'd ask if there was a more popper-ful way to do it since not having to position it myself is why I am here.

There might be a customization I'm missing that will make this work but I'm trying to walk before I run. Apologies if this  just incorrect usage on my part.

**Comment by piecyk** [comment]
@chrisdel101 It looked like you missed setting up the `ref` in the Reference child 

https://codesandbox.io/s/kxl021z623

```jsx
<Reference>
  {({ ref }) => (
    <div ref={ref} className="stop-marker" style={styles} />
  )}
</Reference>
```

**Comment by chrisdel101** [comment]
F! Thanks taking a look
