### ISSUE TITLE
Question: forwarding ref (component instance)

### ISSUE THREAD

**Issue by donifer** [FezVrasta/react-popper#267]
Question:

Hi, I'm struggling to figure out how to use `Reference` when I'm not using a button wrapper with styled-components.

From styled-components docs:
>Passing a ref prop to a styled component will give you one of two things depending on the styled target:
>- the underlying DOM node (if targeting a basic element, e.g. styled.div)
>- a React component instance (if targeting a custom component e.g. extended from React.Component)

Since the ref I'm getting back is the full instance, I'm not quite sure how to use it in `Reference` since `Reference` expects the underlying DOM node. Is there a simple way to solve this without defining a custom `buttonRef` in my styled component and pass it inside?

**Comment by FezVrasta** [comment]
I usually use the `React.forwardRef` utility

**Comment by donifer** [comment]
Do you wrap your `styled-components` with a `React.forwardRef`? Or am I missing something? 🤔 Is there any documentation for this somewhere?

**Comment by diondiondion** [comment]
@donifer 

> Do you wrap your styled-components with a React.forwardRef?

Not sure if you still need help with this, but basically you'll want to use `forwardRef` _in_ the component that you're wrapping. This component needs to attach the passed ref to the element that you want the ref to return (so, most likely the outermost element of the component).

This will make sure that styled-components can forward the ref correctly.
