### ISSUE TITLE
limiting possible placements

### ISSUE THREAD

**Issue by hanford** [FezVrasta/react-popper#270]
Thanks for the library, it's been a life saver and is in many of my projects! 🎉

I was wondering if there was a way to limit placements to either left or right, and never top/bottom.

I'm building a UI with a large cascading menu use `react-popper` and went each sub menu to open only ever on the left or the right.

Thanks again for the great lib!

I've created a codeandbox that is extremely close to the situation I'm trying to make work: https://codesandbox.io/s/7w9yyl2p7x?from-embed

EDIT: 
Nevermind, I think I had a default somewhere that was setting my placement to `auto`, removing that seems to resolve things.

**Comment by hanford** [comment]
Nevermind, I think I had a default somewhere that was setting my placement to `auto`, removing that seems to resolve things.

Will reopen if I run into it again, sorry!

**Comment by hanford** [comment]
On second thought, is there a way to basically do `auto-horizontal` where the placement would be automatic, but only ever left or right?

**Comment by FezVrasta** [comment]
You can define the `flip` modifier behavior to `['left', 'right', 'left']` to make it work only on the horizontal axis

**Comment by hanford** [comment]
Thanks @FezVrasta!
