### ISSUE TITLE
Expose more popper props to manipulate arrow display

### ISSUE THREAD

**Issue by kumarharsh** [FezVrasta/react-popper#271]
There are cases when the popper element is taller (or wider) than the reference element. If you make the window small enough so that the popper flips, the arrow is also flipped. But it's possible that the popper flips and renders *over* the reference element, thus occluding it. This has a side-effect that the arrow is left dangling, pointing to nothing in particular. I was wondering if the `<Popper>` element could expose some prop which would let us *hide* the arrow.

### Reproduction demo

https://codesandbox.io/s/z39x4j94m

Illustrated example:

Normal popper:
![image](https://user-images.githubusercontent.com/760112/53333899-38b91800-391d-11e9-92ea-038451770683.png)

Flipped popper:
![image](https://user-images.githubusercontent.com/760112/53333973-6736f300-391d-11e9-883c-7fdb677ca18c.png)

### Steps to reproduce the problem

1. Create a component where the popper is bigger than its reference element. 
2. Constrain the window size so the popper flips
3. There is not enough information to correctly position the arrow

### What is the expected behavior?

Ideally, I'd expect to *hide* the arrow in case it can't point to the reference element.

### What went wrong?

The only option to modify the arrow element is provided by the `placement` prop, which is not enough.

### Packages versions

- Popper.js: 1.14.1
- react-popper: 1.3.3

**Comment by FezVrasta** [comment]
You can create a custom Popper.js modifier that applies the `display: none` style to the arrow element conditionally based on any logic you'd like.

Take a look at the docs at popper.js.org to learn more.
