### ISSUE TITLE
React 16.8 ?

### ISSUE THREAD

**Issue by LuisSaybe** [FezVrasta/react-popper#272]
Any plans to update to React 16.8 ?

**Comment by sllvn** [comment]
I assume you mean a hooks-style API? That discussion is at https://github.com/FezVrasta/react-popper/issues/241

**Comment by LuisSaybe** [comment]
Sorry, no, I mean updating the current dependency "react" from 16.2 to 16.8

**Comment by FezVrasta** [comment]
We define React as a peer dependency and allow any 16.x version. 16.2 is the one used while we develop the library
