### ISSUE TITLE
Consider exposing a way to access the `referenceNode`

### ISSUE THREAD

**Issue by HHogg** [FezVrasta/react-popper#273]
When creating something like a dropdown with Popper, where the popper element is the dropdown menu and the reference element is a flexible width input element, it is sometimes needed to make the popper element width is the same as the reference element. 

Popper currently has access to the reference node, provided by the `ref` callback from the `Reference` component. It would be very useful to have access to this `referenceNode` (or just the `clientWidth`) to synchronise the popper elements width. 

There are other ways to do this along side Popper, but it would require setting up a way to observe changes to the position and size when Popper is already doing this, and has the information to hand.

The hacky way I'm currently doing this _( 🙈please forgive me)_

```tsx
import { ManagerContext } from 'react-popper/lib/esm/Manager';

<ManagerContext.Consumer>
  { ({ referenceNode }) => /* I now have access to the clientWidth 🙌  */ }
</ManagerContext.Consumer>
```

Awful I know... and by doing it this way no type information either :(

The two ways I've thought this could be added in is either... 

1. Exposing the ManagerContext from the package
1. Providing the `referenceNode` by `InnerPopper` with the other render props. 

Then something like this would work...

```tsx
<Manager>
  <Reference>
    { ({ ref }) => <input ref={ ref } /> }
  </Reference>

  <Popper>
    { ({ referenceNode }) => (
      <DropdownMenu width={ referenceNode && referenceNode.clientWidth }>
        <DropdownMenuItem>...</DropdownMenuItem>
      </DropdownMenu>
    ) }
  </Popper>
</Manager>
```

**Comment by mohsinulhaq** [comment]
why don't you use the `innerRef` prop to `Reference` to grab a ref to the reference element?

**Comment by HHogg** [comment]
@mohsinulhaq I'm using Popper within a UI library so the components are wrapped and there isn't direct access to pass the node from innerRef to the main wrapped popper component. 

I've just realised it is possible to recreate a custom version of ManagerContext and pass it down to the custom wrapped popper component that way, but I just thought that as `referenceNode` was a prop of `InnerProp` already, making it available in the render props would solve this problem in a much easier way... and without it being a crazily specific API change.

**Comment by HHogg** [comment]
I've removed my hack by adding a custom ManagerContext so I'm happy :) and will close this.
