### ISSUE TITLE
Changing Reference Size doesn't recalculate Popper position

### ISSUE THREAD

**Issue by Argonanth** [FezVrasta/react-popper#274]
I'm not sure if this is something that can be easily done and I'm just missing something, but wouldn't this make sense to happen automatically?  I would assume I need to call scheduleUpdate on the PopperProps, although I'm not sure how to call that from the reference.

### Reproduction demo

https://codesandbox.io/s/yvr9py6x4x

### Steps to reproduce the problem

1.  Change size of reference element after the Popper is visible and positioned

### What is the expected behavior?

Popper should recalculate it's position.

### What went wrong?

Popper doesn't move.

### Packages versions

- Popper.js: according to my package-lock it's 1.14.6?
- react-popper: 1.3.3

**Comment by Harsh1796** [comment]
@Argonanth https://codesandbox.io/s/qkm58q0l4w this from @FezVrasta  might help you understand the solution to your issue along with #190 .

Working solution: https://codesandbox.io/s/7zww7kj18q

**Comment by FezVrasta** [comment]
You have to call `scheduleUpdate` when you want to re-position a popper for whatever reason (non related to scroll or window resize events).

https://codesandbox.io/s/548qz1054k

**Comment by designbyadrian** [comment]
@FezVrasta any way of implementing this solution like they did in Semantic UI? https://github.com/Semantic-Org/Semantic-UI-React/pull/3657

**Comment by FezVrasta** [comment]
@designbyadrian from what I see that wouldn't address the OP issue?

**Comment by designbyadrian** [comment]
@FezVrasta they would be able to pass the dimensions as a variable, which, when changed, will trigger the update. The parent component can keep the size of the reference element in its state.

Currently, there is no way for a parent component to tell the popper to update.

**Comment by AMSzura** [comment]
According to Popper docs:

> "You can also trigger an update by setting new options to your Popper instance. This, internally, will call the update() method"

And so, this issue can be solved by adding a custom modifier to options with a reference value that will trigger popper update on change, e.g.:

    modifiers: 
      [
        {
         name: 'ref',
         options: value (e.g. ref client width),
         },
       ],

**Comment by elightbo** [comment]
Looks like the MUI folks added a popperRef prop, so with that you can call update().

```
import { Instance } from "@popperjs/core";

const popperRef = useRef<Instance | null>(null);
popperRef?.current?.update();

<Popper
   ...
   popperRef={popperRef}
 />
```
