### ISSUE TITLE
RefHandler type should also accept SVGElement in TS types (and Flow probably too)

### ISSUE THREAD

**Issue by paolostyle** [FezVrasta/react-popper#277]
Hey. I'm using this library in a component that is basically an SVG and it works great, but TypeScript compiler complains that the type of ref that is passed as a child prop from Reference component is incorrect - it's because of this:
```
type RefHandler = (ref: HTMLElement | null) => void;
```
Seems like changing it to `(ref: HTMLElement | SVGElement | null) => void;` would solve this issue, but I think it would also have to be changed in Flow types. I can make a PR for that, but wanted to ask first if you'd be okay with this change.

**Comment by FezVrasta** [comment]
A PR would be great, thanks!

**Comment by paolostyle** [comment]
I started the implementation but it seems like [Flow doesn't even support SVG types](https://github.com/facebook/flow/pull/4551)... I could change `HTMLElement`s to `Element` but I'm not sure if this is a good idea and I have no experience with Flow - perhaps there's a different way to handle it? Or I can just change it in the TypeScript typings and call it a day. What do you think.
