### ISSUE TITLE
Popper dependency update

### ISSUE THREAD

**Issue by xxia34** [FezVrasta/react-popper#280]
Hi,

Can a new version of react-popper be released with the newest version of popper.js?

Thank you!

### Steps to reproduce the problem

1.  
2.  
3.  

### Packages versions

- Popper.js: 
- react-popper:

**Comment by FezVrasta** [comment]
`react-popper` allows any version equal or above 1.14.4 already.

https://github.com/FezVrasta/react-popper/blob/master/package.json#L63
