### ISSUE TITLE
Replace create-react-contex

### ISSUE THREAD

**Issue by alarstyle** [FezVrasta/react-popper#282]
Replace `create-react-contex` with `mini-create-react-contex`.
It is more optimized and smaller.

**Comment by FezVrasta** [comment]
I was looking at its source code few days ago and the only difference I noticed is the `warning` dependency replaced with a smaller version, is that all it changes?

**Comment by TrySound** [comment]
It also supports esm. Though both depends on shitty `gud` package which requires `global` to be defined. Such webpackisms I'm trying to drop from packages I use.

**Comment by FezVrasta** [comment]
I see, if anyone wants to send a PR please feel free to.

**Comment by TrySound** [comment]
Land PR with fix https://github.com/StringEpsilon/mini-create-react-context/pull/36

**Comment by 7rulnik** [comment]
I have just faced issue with current react-popper@1.3.3. It uses create-react-context@0.2.2 which relies on fbjs@0.8.17 with isomorphic-fetch inside of it. So, it breaks in old browsers without `window.fetch`. 

fbjs was removed in create-react-context@0.3.0 and it's already in master. @FezVrasta could you relase it please?

**Comment by FezVrasta** [comment]
1.3.4 released
