### ISSUE TITLE
Popover position stays the same when content changes.

### ISSUE THREAD

**Issue by davidx1** [FezVrasta/react-popper#283]
### Reproduction demo

https://codesandbox.io/s/great-smoke-sis9b

### Steps to reproduce the problem

1.  Define the content of popper in React state
2.  Set the placement of popper to 'top'
3.  Change the content of the popper when popper is open

### What is the expected behavior?

The content of the popper will stay right above the reference component with no space in between.

### What went wrong?

A gap appears between the popper and the referenced component as we remove content from the poper.

### Any other comments?

You can see the same behavior on the autosuggest component in Material UI, which uses popper under the hood:

![image](https://user-images.githubusercontent.com/12288086/61422425-b8dd2a00-a95f-11e9-945b-da6643812f9f.png)
![image](https://user-images.githubusercontent.com/12288086/61420290-e329ea00-a955-11e9-978a-d32eb47ac5c9.png)

### Packages versions

- Popper.js: 
- react-popper:

**Comment by FezVrasta** [comment]
Popper.js doesn't have any knowledge about the content of the popper, or more generically, the content of the page.

You need to manually call a `scheduleUpdate` to make sure it gets positioned correctly after the content on the page changes.

You can use the ResizeObserver API (with a polyfill for older browsers) to achieve this.

**Comment by davidx1** [comment]
Thanks @FezVrasta for your speedy reply.

I tried doing this and it worked, just like you said it would:
```
        <Popper placement="top">
          {({ scheduleUpdate }) => {
            scheduleUpdate();
            return (
                ....
                ))}
            );
          }}
        </Popper>
```
What do you think of making running scheduleUpdate on every render the default behavior of react-popper?

I understand that in the original popper.js library, popper doesn't have any knowledge about the content of the popper, but the popper react HOC from the react-popper library certainly does know about its content since they are passed in as child props.

Maybe we don't have to do scheduleUpdate every render, maybe we run a shallow compare to see if the child changed, and if it did then we automatically run the scheduleUpdate.

Would love to hear your thoughts

**Comment by FezVrasta** [comment]
That wouldn't cover all the cases, I'm not sure if it would be more helpful or confusing.
