### ISSUE TITLE
css style property receiving 'NaN' in enzyme environment ( when using virtual reference)

### ISSUE THREAD

**Issue by ROUDALI** [FezVrasta/react-popper#284]
im trying to test a click outside event that's suppose to change the state of my Hint component, i'm using react popper and a virtual reference that calculate style from a given reference 
![image](https://user-images.githubusercontent.com/29419489/61456269-89c5b900-a95d-11e9-9bd6-7b1cab7414b3.png)
![image](https://user-images.githubusercontent.com/29419489/61456326-a8c44b00-a95d-11e9-9d3e-8f74545d66a2.png)
the problem is that when i want to test an event 
for example:
![image](https://user-images.githubusercontent.com/29419489/61456399-d90be980-a95d-11e9-9f4f-53b820645c26.png)
 i got this:
![image](https://user-images.githubusercontent.com/29419489/61456440-efb24080-a95d-11e9-8270-07265a5ebf98.png)
anyone have an idea on how to solve this ...

**Comment by FezVrasta** [comment]
Unfortunately Popper.js doesn't work with JSdom, you need to mock Popper.js using the instructions provided in the README
