### ISSUE TITLE
NPM warning of using deprecated package

### ISSUE THREAD

**Issue by prayadav** [FezVrasta/react-popper#285]
- npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 
I am hitting deprecated warning against core-js v1.2.7, which is used by react-popper@1.3.3 [ as illustrated in the below screen-grab 
└─┬ reactstrap@8.0.1
  └─┬ react-popper@1.3.3
    └─┬ create-react-context@0.2.2
      └─┬ fbjs@0.8.17
        └── core-js@1.2.7
Strangely, when I looked at react-popper package.json, I found no reference of > create-react-context@0.2.2 Not sure what is causing this deprecation warning

**Comment by FezVrasta** [comment]
I need to cut a new release with https://github.com/FezVrasta/react-popper/pull/281 to fix this

**Comment by kevinbarabash** [comment]
bump
