### ISSUE TITLE
Problem with import statement.

### ISSUE THREAD

**Issue by richtera** [FezVrasta/react-popper#287]
https://github.com/FezVrasta/react-popper/blob/8994933c430e48ab62e71495be71e4f440b48a5a/src/Reference.js#L3

I believe this should say import from "./warning" or something similar. It's blowing up my webpack compile.
I am switching to 1.2.1 to see if that's better. Basically it works at first when using webpack in dev mode, but then it sees the ESM file and goes wrong.
Thanks
Andy

**Comment by FezVrasta** [comment]
warning is a dependency, that's how you import them

**Comment by richtera** [comment]
Hmmm, somehow it's not resolving it. Will check. It makes sense it would be a dep but it's not showing up in the node_modules folder and doing install warning didn't seem to work. Thanks for the response.

**Comment by richtera** [comment]
So it works on the initial compile, but whenever I make code changes the build fails.
![image](https://user-images.githubusercontent.com/708186/61567735-a42b8f80-aa4e-11e9-9a81-4ec57e9d57b0.png)
Hmmm, I'll play with it a bit. But it's weird that it's this random module here, Warning is installed in the root node_modules folder and not a child of react-popper.

**Comment by FezVrasta** [comment]
That's called dependency hoisting, it's common practice in js package managers

**Comment by richtera** [comment]
Found it. All my fault. It's weird that it picked this module to fail. I had a defunct webpack-dev-server running :-( I am so sorry. I wasted quite a lot of time on such silly ness.
