### ISSUE TITLE
Changing arrow style conditionally

### ISSUE THREAD

**Issue by sonakshiChomal** [FezVrasta/react-popper#288]
### What went wrong?

I need to change the popover color on the basis of a condition.

So if the flag condition is true the popover will be gray and if the flag will be false the popover will be white.

am able to do that but, popover color changes but the arrow color remains white always.

Is there a way or a prop that can change the color of the arrow with the popover.

Overriding the style is not possible as in my case the color changes on fly (based on a flag from services)

### Packages versions

- Popper.js: ^1.15.0
- react-popper: ^1.3.3

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
