### ISSUE TITLE
Arrow Style 'Top' Positioning Always Empty String

### ISSUE THREAD

**Issue by ragurney** [FezVrasta/react-popper#291]
### Reproduction demo
* Custom repro with Fela styles: https://codesandbox.io/s/popper-with-style-1d0ho
* Repro using the template. Console shows top is always an empty string: https://codesandbox.io/s/react-popper-v1x-issue-template-21h5z

### Steps to reproduce the problem

1.  Log the `arrowProps.style`
2.  Note that `top` offset is always the empty string ''
3.  😢 

### What is the expected behavior?
The `top` value in `arrowProps.style` is updated dynamically depending on position. 

### What went wrong?
The `top` value in `arrowProps.style` is always the empty string, regardless of position.

### Packages versions
- Popper.js: ^1.14.4
- react-popper: 1.3.3

**Comment by FezVrasta** [comment]
The arrow offset only provides the value needed to center the arrow within the popper.

In your case, the popper is on bottom of the reference element so you only get the left arrow offset since that's what you need to center it properly.

I hope the explanation is helpful.

**Comment by ragurney** [comment]
It is, thank you. Apologies, I was a little confused about what was expected to be supported for the arrow. Thanks for the clarification!

**Comment by FezVrasta** [comment]
Docs suck, any improvement is very welcome. Thank you 👍
