### ISSUE TITLE
TypeError: Cannot read property 'setTargetNode' of undefined

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [FezVrasta/react-popper#293]
### Steps to reproduce the problem

1.  Install reactstrap 6.1.0
2.  run application
3.  it will show above error in the console and application will stop working.

### What is the expected behavior?

Application should work properly.

### What went wrong?
Using reactstrap in application which have dependency on the react-popper which causing this erros in console and application stops working.

### Packages versions
v 1.3.3
- Popper.js: 
- react-popper:

**Comment by mohsinulhaq** [comment]
> 2. run application

Which application?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
