### ISSUE TITLE
Breaking change with AMD dependencies

### ISSUE THREAD

**Issue by artola** [FezVrasta/react-popper#310]
### Steps to reproduce the problem

For v1.3.4 the file `index.umd.min.js` contains a different list of externals than v1.3.3.

v1.3.3 defines the following dependencies `define(["exports","react","popper.js"] ...` but v1.3.4 `define(["exports","react","create-react-context","popper.js","warning"] ...`.
As so it is a breaking change (at least minor) and not just a patch.

### Any other comments?

For example `react-router` bundle `tiny-warning` and others.

At leat in AMD, having many small dependencies becomes a problem, too many request, therefore I will need to bundle these dependencies altogether with react-popper or other utils.

### Packages versions

- react-popper: 1.3.4

**Comment by FezVrasta** [comment]
Hi, thanks for the issue. I wouldn't think a new dependency a breaking change, that would limit a lot what a non-major version can do...

I'll try to keep it in mind in the future, you may consider to switch to a modern module system such as ES modules so that this kind of issue doesn't affect you.

**Comment by artola** [comment]
> Hi, thanks for the issue. I wouldn't think a new dependency a breaking change, that would limit a lot what a non-major version can do...
> 
> I'll try to keep it in mind in the future, you may consider to switch to a modern module system such as ES modules so that this kind of issue doesn't affect you.

Thanks for prompt reply. It is not about a new dependency,  it is more about  changing the bundling what leads to a breaking change, because it will require a change in the consumers.
I love ES modules, but there is not "one fits all", and in my case I use the ES version for `development` while AMD for `production`.

I just modified our bundler to add these dependencies in `bundle`. No problem. Thanks again, for me this issue can be closed.

**Comment by FezVrasta** [comment]
The bundle is automatically generated so there's not much I can do, when a new dependency is added, the bundle is updated.

Thanks again for making me aware of this situation.
