### ISSUE TITLE
v1.3.5 broken in React@15

### ISSUE THREAD

**Issue by tybro0103** [FezVrasta/react-popper#316]
### Reproduction demo

https://codesandbox.io/s/react-popper-v1x-issue-template-sp9mn

### Steps to reproduce the problem

With `react@15.6.2` installed, `react-popper@1.3.4` works fine, but `react-popper@1.3.5` does not.

### What is the expected behavior?

That it functions without errors.

### What went wrong?

The following error is repeatedly thrown:
```
Uncaught RangeError: Maximum call stack size exceeded
    at Popper (Popper.js:200)
    at StatelessComponent.render (ReactCompositeComponent.js:42)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:743)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:721)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:642)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
```

With certain usage, I've seen `react-popper` still function despite this error, but with half-second delay. With other usages, I've seen `react-popper` not work at all.

### Any other comments?

The react peerDep is `0.14.x || ^15.0.0 || ^16.0.0`, but the devDep is set to `16.9.0`. This is a no-no. React does not provide any way to ensure support for 3 major versions at a time, and if you do support 2 major versions at a time (please do), then your devDep should be on the lower of the 2 majors. If it works in the lower major with no deprecation warnings, then you have a guarantee that it will work in the higher major as well.

### Packages versions

- Popper.js: 
- react-popper:

**Comment by tybro0103** [comment]
Ok so this partially due to the way were using the ref passed into the FaCC function (see the codesandbox link). Maybe we shouldn't be doing that, but still... it works fine if I upgrade to `react@16`, and it works fine if I downgrade to `react-popper@1.3.4`.

**Comment by JonathanAquino** [comment]
This is a breaking, backwards incompatible change for us.

Could you revert the changes and release the revert as v1.3.6, then publish the new changes as 2.0.0?

![image](https://user-images.githubusercontent.com/90288/68345755-f4cf0300-00a6-11ea-8c47-210ded2b4bf4.png)

**Comment by piecyk** [comment]
Looks like `create-react-context` doesn't work exactly as `React.createContext` 😞 

This is regression of https://github.com/FezVrasta/react-popper/pull/266/files#r251516842

we need to fallback to previous check, basic fix this line, and clear the node on unmount
https://github.com/FezVrasta/react-popper/blob/master/src/Manager.js#L16

```js
  setReferenceNode = (newReferenceNode: ?HTMLElement) => {
    if (newReferenceNode && this.referenceNode !== newReferenceNode) {
      this.referenceNode = newReferenceNode;
      this.forceUpdate();
    }
  };

  componentWillUnmount() {
    this.referenceNode = null;
  }
```

Would be awesome to run tests on multiple versions of React in CI plus drop enzyme and just replay on react-dom, and react-test-renderer, simplify tests 

```
  it(`should not throw 'Maximum call stack size exceeded'`, () => {
    expect(() => {
      ReactDOM.render(
        <Manager>
          <Reference>
            {({ ref }) => (
              <div
                ref={node => {
                  ref(node);
                }}
              >
                hello
              </div>
            )}
          </Reference>
        </Manager>,
        document.createElement('div')
      );
    }).not.toThrow();
  });
```

**Comment by tybro0103** [comment]
@piecyk  Thank you bunches!

**Comment by JonathanAquino** [comment]
@piecyk @FezVrasta Thanks!
